spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeader: "*"
            allowedMethod:
              - GET
              - POST
              - PUT
              - DELETE